language: bash
install:
- curl -sLf -o kubeaudit.tar.gz https://github.com/Shopify/kubeaudit/releases/download/v0.12.0/kubeaudit_0.12.0_linux_amd64.tar.gz
- tar -zxvf kubeaudit.tar.gz
- chmod +x kubeaudit
script:
- ./kubeaudit nonroot -f deployment.yaml &> errors
- if [ -s errors ] ; then cat errors; exit -1; fi
